app1/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns
from django.conf.urls import url


urlpatterns = patterns(
    'app1.views',
    url(r'^$', 'ma_list', name='ma_list'),
    url(r'^add/$', 'ma_create', name='ma_create'),
    url(r'^(?P<pk>\d+)/$', 'ma_detail', name='ma_detail'),
    url(r'^(?P<pk>\d+)/delete/$', 'ma_delete', name='ma_delete'),
    url(r'^(?P<pk>\d+)/edit/$', 'ma_update', name='ma_update'),
    url(r'^(?P<pk>\d+)/history/$', 'get_history_ModelA', name='ma_history'),
    url(r'^(?P<pk>\d+)/revert/(?P<rev_pk>\d+)/$', 'revert_modela_to_revision',
        name='ma_revert'),
)

rev/urls.py
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^', include('app1.urls', namespace='app1')),
    url(r'^', include('rev_history.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

rev_history/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('rev_history.views',
    url(r'^history/$', 'history_list', name='history-list'),
)

app1/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.db import transaction
from django.utils import timezone
import reversion


reversion.register(User)


@reversion.register
class ModelA(models.Model):
    user = models.ForeignKey(User, related_name='us')

    attr1 = models.CharField(max_length=50, blank=True)

    is_active = models.BooleanField(default=True, blank=True)

    updated_by_user = models.ForeignKey(User, related_name='uus')

    created_at = models.DateTimeField(auto_now_add=True, default=timezone.now,
                                      editable=False)

    updated_at = models.DateTimeField(auto_now=True, default=timezone.now,
                                      editable=False)

    def save(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            if self.id:
                reversion.set_comment("updated ModelA")
            else:
                reversion.set_comment("created ModelA")
            reversion.set_user(self.updated_by_user)
            super(ModelA, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{0} - {1}'.format(self.user.username, self.attr1)

rev_history/models.py
from django.db import models

# Create your models here.

app1/forms.py
# -*- coding: utf-8 -*-

from django import forms
from app1.models import ModelA

class ModelAForm(forms.ModelForm):

    class Meta:
        model = ModelA
        exclude = ('updated_by_user', )

app1/views.py
# -*- coding: utf-8 -*-

from app1.forms import ModelAForm
from app1.models import ModelA
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
import reversion


class ModelADetailView(DetailView):
    model = ModelA
    template_name = 'app1/ma_detail.html'


class ModelACreateView(CreateView):
    form_class = ModelAForm
    success_url = reverse_lazy('app1:ma_list')
    template_name = 'app1/ma_form.html'

    def form_valid(self, form):
        form.instance.updated_by_user = self.request.user
        return super(ModelACreateView, self).form_valid(form)


class ModelAUpdateView(UpdateView):
    model = ModelA
    form_class = ModelAForm
    success_url = reverse_lazy('app1:ma_list')
    template_name = 'app1/ma_form.html'

    def form_valid(self, form):
        form.instance.updated_by_user = self.request.user
        return super(ModelAUpdateView, self).form_valid(form)


class ModelADeleteView(DeleteView):
    model = ModelA
    success_url = reverse_lazy('app1:ma_list')
    template_name = 'app1/ma_delete.html'


class ModelAListView(ListView):
    model = ModelA
    template_name = 'app1/ma_list.html'


def get_history_ModelA(request, pk):
    template = 'app1/ma_history.html'
    ma = get_object_or_404(ModelA, pk=pk)
    version_list = reversion.get_for_object(ma)
    context = { 'obj_pk': pk, 'version_list': version_list }
    return render_to_response(template, RequestContext(request, context))


def revert_modela_to_revision(request, pk, rev_pk):
    ma = get_object_or_404(ModelA, pk=pk)
    version = reversion.get_for_object(ma).get(id=rev_pk)

    with transaction.atomic(), reversion.create_revision():
        reversion.set_comment("reverted ModelA")
        reversion.set_user(request.user)
        version.revision.revert()

    return HttpResponseRedirect(reverse_lazy('app1:ma_detail', args=(ma.pk,)))


ma_list = ModelAListView.as_view()
ma_detail = ModelADetailView.as_view()
ma_delete = ModelADeleteView.as_view()
ma_update = ModelAUpdateView.as_view()
ma_create = ModelACreateView.as_view()

rev_history/views.py
from django.http import HttpResponse
from reversion.models import Version
from django.contrib.admin.models import LogEntry
import json

def history_list(request):
    history_list = Version.objects.all().order_by('-revision__date_created')

    data = []

    for i in history_list:
        data.append({
            'date_time': str(i.revision.date_created),
            'user': str(i.revision.user),
            'object': i.object_repr,
            'type': i.content_type.name,
            'comment': i.revision.comment
        })

    data_ser = json.dumps(data)
    return HttpResponse(data_ser, content_type="application/json")

app1/templates/app1/base.html
<html>
    <head>
        <title>{% block title %} App1 {% endblock title %}</title>
        {% block styles %} {% endblock styles %}
    </head>
    <body>
        {% block content %} {% endblock content %}
        {% block scripts %} {% endblock scripts %}
    </body>
</html>

app1/templates/app1/ma_delete.html
{% extends "app1/base.html" %}

{% load i18n %}

{% block content %}
<h2>Delete</h2>

<p>{% blocktrans with escaped_object=object %}Are you sure you want to delete the "{{ escaped_object }}"? {% endblocktrans %}</p>

<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans "Yes, I am sure" %}"/>
</form>

<a href="{% url 'app1:ma_list' %}">{% trans "Back" %}</a>
{% endblock content %}

app1/templates/app1/ma_detail.html
{% extends "app1/base.html" %}

{% load i18n %}

{% block content %}

<h2>Detail</h2>

<p>{{ object }}</p>

<a href="{% url 'app1:ma_list' %}">{% trans "Back" %}</a>

{% endblock content %}

app1/templates/app1/ma_form.html
{% extends "app1/base.html" %}

{% load i18n %}

{% block content %}

<h2>Create</h2>

<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}"/>
</form>

<a href="{% url 'app1:ma_list' %}">{% trans "Back" %}</a>
{% endblock content %}

app1/templates/app1/ma_history.html
{% extends "app1/base.html" %}

{% load i18n %}

{% block content %}
<h2>History</h2>

{% if version_list %}
    <table>
        <thead>
            <tr>
                <th>{% trans 'Date/time' %}</th>
                <th>{% trans 'User' %}</th>
                <th>{% trans 'Comment' %}</th>
                <th>{% trans 'Revert' %}</th>
                <th>{% trans 'Data' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for ver in version_list %}
                <tr>
                    <th scope="row">{{ ver.revision.date_created }}</th>
                    <td>
                        {% if ver.revision.user %}
                            {{ ver.revision.user.get_username }}
                            {% if ver.revision.user.get_full_name %} ({{ ver.revision.user.get_full_name }}){% endif %}
                        {% else %}
                            &mdash;
                        {% endif %}
                    </td>
                    <td>{{ ver.revision.comment|linebreaksbr|default:"" }}</td>
                    <td><a href="{% url 'app1:ma_revert' obj_pk ver.pk %}">revert</a></td>
                    <td>{{ ver.field_dict }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>{% trans "This object doesn't have a change history." %}</p>
{% endif %}

<a href="{% url 'app1:ma_list' %}">{% trans "Back" %}</a>

{% endblock content %}

app1/templates/app1/ma_list.html
{% extends "app1/base.html" %}

{% load i18n %}

{% block content %}
<h2>List</h2>
<a href="{% url 'app1:ma_create' %}">{% trans "Create" %}</a>

<table>
    <tbody>
        {% for object in object_list %}
            <tr>
                <td><a href="{% url 'app1:ma_detail' object.pk %}">{{ object }}</a></td>
                <td><a href="{% url 'app1:ma_update' object.pk %}">update</a></td>
                <td><a href="{% url 'app1:ma_history' object.pk %}">history</a></td>
                <td><a href="{% url 'app1:ma_delete' object.pk %}">delete</a></td>
            </tr>
        {% empty %}
            {% trans "Nothings here!" %}
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'app1:ma_list' %}">{% trans "Back" %}</a>

{% endblock content %}